name: cacao-accounting
base: core24
version: "2024.05.07"
summary: Accounting solution for small and medium-sized businesses
description: |
  Accounting solution for the finance management of small and medium-sized companies that includes
  modules for Accounts Payables, Accounts Receivables, Inventory, Treasury and General Accounting
grade: devel
confinement: strict
apps:
  cacao-accounting-desktop:
    command: /bin/cacao_accounting_desktop
    plugs: [home]
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

parts:
  cacao-accounting:
    plugin: python
    source-type: git
    source: https://github.com/cacao-accounting/cacao-accounting-desktop.git
    python-requirements:
      - requirements.txt
