name: cacao-accounting-desktop
title: Cacao Accounting Software
summary: Accounting solution for small and medium-sized businesses
base: core26
version: "2026.7.11"
license: Apache-2.0
grade: stable
confinement: strict
icon: snap/gui/cacao-accounting-desktop.png
issues: https://github.com/cacao-accounting/cacao-accounting/issues
source-code: https://github.com/cacao-accounting/cacao-accounting-snap
website: https://cacaoaccounting.com
description: |
  Accounting solution for the finance management of small and medium-sized companies that includes
  modules for Accounts Payables, Accounts Receivables, Inventory, Treasury and General Accounting.
  Cacao Accounting can generate reports such as Balance Sheet, Profit and Loss Statements, Trial Balance,
  Journal and General Ledger, you can also export your information to analyze it with a spreadsheet or a
  business intelligence tool.

apps:
  cacao-accounting-desktop:
    command: bin/cacao_accounting_desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

parts:
  cacao-accounting-desktop:
    plugin: python
    source-type: git
    source: https://github.com/cacao-accounting/cacao-accounting-desktop.git
    python-requirements:
      - requirements.txt
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
      - python3-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libgdk-pixbuf-2.0-dev
      - libxml2-dev
      - libxslt1-dev
      - libharfbuzz-dev
    stage-packages:
      - python3.14
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libcairo2
      - libgdk-pixbuf-2.0-0
      - libxml2-16
      - libxslt1.1
      - libharfbuzz0b
      - libgl1
      - libegl1
      - libxkbcommon0
      - libnss3
      - libnspr4
      - libdbus-1-3
